### PR TITLE
remove some redundant state machines

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by pavelfeldman** [comment]
What's the rationale behind the change? Also looks like bots aren't happy.

**Comment by SimonCropp** [comment]
gimme some time to have a look at the bots

**Comment by SimonCropp** [comment]
the rational is perf

**Comment by pavelfeldman** [comment]
I know nothing about .NET, but I hope implications of this are negligible. Even if there is a microbenchmark that can detect this, I don't think we would see it in the Playwright setting. I'm Ok with accepting it if some code style / best practices suggest returning Task though.

**Comment by SimonCropp** [comment]
i should note this approach is already used in many places in the code base. eg 

```
        private Task ExposeBindingAsync(string name, Delegate callback, bool handle = false)
        {
            if (Bindings.ContainsKey(name))
            {
                throw new PlaywrightException($"Function \"{name}\" has been already registered");
            }

            Bindings.Add(name, callback);

            return _channel.ExposeBindingAsync(name, handle);
        }
```

**Pull request merged**
