### PR TITLE
Enabled channel and slowmo environment variables for testing

### PR DESCRIPTION
**Pull request by mlankamp**
Enabled 2 additional environment variables for running tests with mstest or nunit. Allows running on a chromium channel and allows slowmo to see what's going on.

**Linux**
```
HEADED=1 CHANNEL=chrome-dev SLOWMO=1000 dotnet test
```

**Windows** 
```
set HEADED=1
set CHANNEL=chrome-dev
set SLOWMO=1000
dotnet test
```

### CODE REVIEW

**Comment by mlankamp** [comment]
Solution for #1730

**Comment by avodovnik** [comment]
Thanks for the contribution!

I've actually started work on a feature that would also enable this, I have a draft PR up at #1743. I want to make some changes to the way how configuration can be done, outside of "just" using env variables.

**Comment by mlankamp** [comment]
The focus now is on environment variables, but how could we also use runsettings files for configuration? 

The settings are for browserlaunch options, but maybe we want to enable some default context options also, for example the locale or override the user agent.

**Comment by vertonghenb** [comment]
Is there a reason why this is not being approved?

**Pull request closed without merging**
