### PR TITLE
make Waiter IAsyncDisposable

### PR DESCRIPTION
**Pull request by SimonCropp**
avoids discarding the task from SendMessageToServerAsync

### CODE REVIEW

**Comment by pavelfeldman** [comment]
Could you elaborate? Those messages are supposed to be fire and forget. Does it cause errors? Can we silent-catch locally?

**Comment by SimonCropp** [comment]
> Those messages are supposed to be fire and forget

so it is ok for them to continue running during appdomain shutdown?

**Comment by pavelfeldman** [comment]
I believe so. Those are I/O against the driver connection. As we exit, driver process exits and the transport as terminated. So all the pending I/Os fail, including this one.

**Comment by SimonCropp** [comment]
ok

**Pull request closed without merging**
